modLoader = "javafml"
loaderVersion = "[65,)"
issueTrackerURL = "https://github.com/Potion-Studios/Wayfinder/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Adds Wayfinder Entity that can find any biome
'''
displayURL="https://potionstudios.net/"
logoFile = "wayfinder.png"

[[dependencies.wayfinder]]
modId = "forge"
mandatory = true
versionRange = "[65.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
mandatory = true
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "geckolib"
mandatory = true
versionRange = "[5.5.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "biomeswevegone"
mandatory = false
versionRange = "[4.3.3,)"
ordering = "AFTER"
side = "BOTH"