modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
'''
#logoFile = ""

[[dependencies.wayfinder]]
modId = "forge"
mandatory = true
versionRange = "[52.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "geckolib"
mandatory = true
versionRange = "[4.7,)"
ordering = "AFTER"
side = "BOTH"