modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL = "https://github.com/Potion-Studios/Wayfinder/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Adds Wayfinder Entity that can find any biome
'''
displayURL="https://potionstudios.net/"
#logoFile = ""

[[dependencies.wayfinder]]
modId = "forge"
mandatory = true
versionRange = "[52.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "geckolib"
mandatory = true
versionRange = "[4.7.3,)"
ordering = "AFTER"
side = "BOTH"