org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.1

archives_base_name=Wayfinder
mod_version=1.2.8-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.19.5
fabric_api_version=0.116.17

forge_version=52.1.16

neoforge_version=21.1.256

parchment=2024.11.17

devauth_version=1.2.2

geckolib_version=4.9.3

bwg_version=2.6.2
