modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Potion-Studios/Wayfinder/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Adds Wayfinder Entity that can find any biome
'''
displayURL="https://potionstudios.net/"
logoFile = "wayfinder.png"

[[dependencies.wayfinder]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "wayfinder-common.mixins.json"