modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Potion-Studios/Wayfinder/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Adds Wayfinder Entity that can find any biome
'''
displayURL="https://potionstudios.net/"
logoFile = "wayfinder.png"

[[dependencies.wayfinder]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "geckolib"
type = "required"
versionRange = "[5.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "biomeswevegone"
type = "optional"
versionRange = "[4.3.3,)"
ordering = "AFTER"
side = "BOTH"
